/// Model for questions generated by Hybrid Oracle (Pattern + AI)
class GeneratedQuestion {
  final String id;
  final String text;
  final String difficulty; // 'easy', 'medium', 'hard'
  final int marks;
  final String concept;
  final String source; // 'pattern' or 'ai'
  final List<String> conceptTags;
  
  // JSXGraph visualization fields (from AI Oracle)
  final String? jsxGraphCode; // JavaScript code for interactive diagram
  final List<double>? graphBoundingBox; // [x1, y1, x2, y2]
  final bool? showAxis;
  final bool? showGrid;
  final bool requiresGraphInteraction; // True for "drag point" questions
  
  // Answer validation fields
  final String answerType; // 'numeric', 'text', 'graph_coordinate', 'multiple_choice'
  final dynamic correctAnswer; // Can be number, string, or Map for coordinates
  
  // Solution data
  final List<String> solutionSteps;
  final String finalAnswer;
  final List<Map<String, String>> socraticHints;

  GeneratedQuestion({
    required this.id,
    required this.text,
    required this.difficulty,
    required this.marks,
    required this.concept,
    required this.source,
    required this.conceptTags,
    this.jsxGraphCode,
    this.graphBoundingBox,
    this.showAxis = true,
    this.showGrid = true,
    this.requiresGraphInteraction = false,
    required this.answerType,
    required this.correctAnswer,
    required this.solutionSteps,
    required this.finalAnswer,
    required this.socraticHints,
  });

  factory GeneratedQuestion.fromJson(Map<String, dynamic> json) {
    return GeneratedQuestion(
      id: json['question_id'],
      text: json['question_text'],
      difficulty: json['difficulty'].toString(),
      marks: json['marks'],
      concept: json['concept'],
      source: json['source'],
      conceptTags: List<String>.from(json['concept_tags'] ?? []),
      jsxGraphCode: json['jsxgraph_code'],
      graphBoundingBox: json['graph_bounding_box'] != null
          ? List<double>.from(json['graph_bounding_box'])
          : null,
      showAxis: json['show_axis'] ?? true,
      showGrid: json['show_grid'] ?? true,
      requiresGraphInteraction: json['requires_graph_interaction'] ?? false,
      answerType: json['answer_type'],
      correctAnswer: json['correct_answer'],
      solutionSteps: List<String>.from(json['solution_steps'] ?? []),
      finalAnswer: json['final_answer'],
      socraticHints: (json['socratic_hints'] as List?)
              ?.map((hint) => Map<String, String>.from(hint))
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'question_id': id,
      'question_text': text,
      'difficulty': difficulty,
      'marks': marks,
      'concept': concept,
      'source': source,
      'concept_tags': conceptTags,
      'jsxgraph_code': jsxGraphCode,
      'graph_bounding_box': graphBoundingBox,
      'show_axis': showAxis,
      'show_grid': showGrid,
      'requires_graph_interaction': requiresGraphInteraction,
      'answer_type': answerType,
      'correct_answer': correctAnswer,
      'solution_steps': solutionSteps,
      'final_answer': finalAnswer,
      'socratic_hints': socraticHints,
    };
  }
}
